### ISSUE TITLE
docs(ja): guides/directory-structure/layouts.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#105]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by konu96** [comment]
@inouetakuya 
この Issue の翻訳をしたいです

**Comment by inouetakuya** [comment]
よろしくお願いします！
