### ISSUE TITLE
docs(ja): guides/directory-structure/components.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#108]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by Katakuranatsumi** [comment]
@inouetakuya 
こちら良ければ翻訳させていただければと思いますmm

**Comment by inouetakuya** [comment]
お願いします！！

**Comment by aytdm** [comment]
@Katakuranatsumi こんばんは。こちら状況いかがでしょうか？忙しい場合は巻き取れるので遠慮なく仰ってください

**Comment by Katakuranatsumi** [comment]
@aytdm 
PullRequestの作成が遅くなっており、大変失礼致しました🙇‍♀️
こちら今週末中には出すように致しますmm

**Comment by aytdm** [comment]
ありがとうございます
急かすつもりはなかった（もしそう感じたならすみません🙇‍♂️）ので、今週末でなくともご都合のいいタイミングで大丈夫です👍
どうぞよろしくお願いします

**Comment by Katakuranatsumi** [comment]
@inouetakuya @aytdm 
当issueのPullRequestのレビューありがとうございました🙇‍♀️
