### ISSUE TITLE
docs(ja): guides/concepts/server-side-rendering.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#111]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by mrbigass** [comment]
初めまして
よろしければ翻訳やらせてください

**Comment by inouetakuya** [comment]
よろしくお願いします！

**Comment by aytdm** [comment]
わ、ありがとうございます！よろしくお願いします🙌

**Comment by aytdm** [comment]
ja フォルダにいのうえさんがコミットした以降で[原文に更新が入っている](https://github.com/vuejs-jp/ja.nuxtjs.org/issues/230)ので、取り込んでいただけると助かりますmm
