### ISSUE TITLE
docs(ja): guides/directory-structure/assets.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#115]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by Shohei-Japan** [comment]
@inouetakuya @aytdm 
こちらの issue の翻訳を担当させていただけますでしょうか。

**Comment by inouetakuya** [comment]
よろしくお願いします！
