### ISSUE TITLE
docs(ja): guides/directory-structure/dist.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#124]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by Shohei-Japan** [comment]
@inouetakuya @aytdm 
Vue3 の翻訳でも少しお手伝いさせていただいた者です。
ぜひこちらの翻訳でも何かお力添えできればと思っているのですが、この issue の翻訳を担当させていただけますでしょうか。

**Comment by aytdm** [comment]
ありがとうございます。よろしくお願いします🙏

**Comment by inouetakuya** [comment]
> Vue3 の翻訳でも少しお手伝いさせていただいた者です。

知ってるしw

心強い！よろしくお願いします！！
