### ISSUE TITLE
docs(ja): guides/directory-structure/pages.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#143]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by daisuke85a** [comment]
@inouetakuya
@aytdm
@53able

こちらの翻訳やらせてください！

**Comment by aytdm** [comment]
@daisuke85a よろしくお願いします🙌
