### ISSUE TITLE
docs(ja): guides/directory-structure/store.md

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#146]
## 日本語翻訳ガイド

https://github.com/vuejs-jp/ja.nuxtjs.org/wiki

## 備考

https://ja.nuxtjs.org/api ( https://github.com/nuxt/nuxtjs.org/tree/master/content/ja/api ) に類似のドキュメントがあるので、翻訳する際に参考にしてください。

## 関連 Issue

- https://github.com/vuejs-jp/ja.nuxtjs.org/issues/22
- https://github.com/nuxt/nuxtjs.org/issues/544

**Comment by resessh** [comment]
@inouetakuya @aytdm @53able 
https://github.com/vuejs-jp/ja.nuxtjs.org/issues/79 の前提条件として翻訳が必要なので、こちらをやらせてください 🙏

**Comment by aytdm** [comment]
@resessh ありがとうございます、よろしくお願いします！
（#79 は `guide` の方の修正の意味で残していました。分かりづらくてすみません :bow: ）
