### ISSUE TITLE
ci: content/ja に対して textlint を導入する

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#221]
## 解決したい問題

プルリクエストのレビューにおいて、翻訳された文章に対してではなく、書式についての指摘は、レビュアーにとってもレビュイーにとってもあまり有意義とはいえないので、レビュアーが指摘する前に書式の誤りに気付けるようにしたいと思います。

## 問題の解決のために

- textlint を導入する
- content/ja に対してチェックを行う
- チェックを CI で実行する
  - git push されたタイミングで実行
  - 対象ブランチ: すべて
- チェック対象
  - jp.vuejs.org の https://github.com/vuejs/jp.vuejs.org/blob/lang-ja/.textlintrc から移植しようかと考えましたが、jp.vuejs.org の textlint のバージョンは著しく古かったので、参考程度に留め、そのまま移植するのは止めようと思います
  - はじめからパーフェクトを目指さず、これまで頻繁に指摘して来た事項に限定してよいと考えています
    - JTF日本語標準スタイルガイドに沿っているか
    - 半角スペースでアルファベット両端を入れて読みやすく

## 参考

- [Nuxt.js 公式ドキュメント日本語翻訳ガイド](https://github.com/vuejs-jp/ja.nuxtjs.org/wiki)
- 最近書式について指摘したプルリクエストの例
  - https://github.com/nuxt/nuxtjs.org/pull/1023

**Comment by inouetakuya** [comment]
@aytdm @53able 

これをやろうと思いますが「問題の解決のために」に書いた仕様的なところについて何か気になる点などあればコメントください 🙏

**Comment by inouetakuya** [comment]
あ、こっち https://github.com/vuejs-jp/ja.vuejs.org/blob/lang-ja/package.json#L6 のほうは textlint のバージョン新しい！

- [textlint の導入 by Katakuranatsumi · Pull Request #97 · vuejs-jp/ja.vuejs.org](https://github.com/vuejs-jp/ja.vuejs.org/pull/97)

で導入されたのか 📝

**Comment by 53able** [comment]
@inouetakuya ありがとうございます！　
拝見しました！
問題ないと思っています！

**Comment by inouetakuya** [comment]
確認ありがとうございます！

**Comment by aytdm** [comment]
とてもよいですね！ありがとうございます
nuxtjs.org は github actions をメインにつかっているので、actions + [reviewdog](https://github.com/reviewdog/reviewdog) とか良いんじゃないかなぁと思っています :)

**Comment by inouetakuya** [comment]
https://github.com/reviewdog/reviewdog は初めて知りました！良さそう！！（情報ありがとうございます！）

あんまり時間かからないと思うけど、今週末はちょっと珍しく用事があったりするので、来週あたりにやってしまおうと考えています！
