### ISSUE TITLE
Sync upstream workflow run failed（git push origin master 時に失敗）

### ISSUE THREAD

**Issue by inouetakuya** [vuejs-jp/ja.nuxtjs.org#235]
Sync upstream workflow が `git push origin master` 時に失敗しているため対応する。

- https://github.com/vuejs-jp/ja.nuxtjs.org/actions/runs/455358139
- https://github.com/vuejs-jp/ja.nuxtjs.org/actions/runs/453641269

```
Run git push origin master
To https://github.com/vuejs-jp/ja.nuxtjs.org
 ! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/links.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/vuejs-jp/ja.nuxtjs.org'
Error: Process completed with exit code 1.
```

**Comment by aytdm** [comment]
起票ありがとうございますmm

> refusing to allow a GitHub App to create or update workflow `.github/workflows/links.yml` without `workflows` permission

workflow を許可した PAT の設定が必要そうですね
いのうえさんは vuejs-jp アカウントでトークンを作れるでしょうか？私は権限がないので、もしできるならお願いしたいです

ref: https://jessehouwing.net/cannot-push-to-github-without-workflow-scope/

**Comment by inouetakuya** [comment]
動けていなくてごめんなさい、今週末（1/23、1/24）に対応します！ 💪

**Comment by aytdm** [comment]
ありがとうございますmm（今、設定で Action 止めています）

**Comment by inouetakuya** [comment]
## 進捗ダメです...

> いのうえさんは vuejs-jp アカウントでトークンを作れるでしょうか？

設定ページを確認してみたのですが Organization アカウントで PAT を発行するメニューが見つからず。もうちょい調べないと解決方法が分からなさそうです。

![image](https://user-images.githubusercontent.com/634357/105784391-0fe3a680-5fbc-11eb-8dc3-5631c286a4c5.png)

あと、仮に PAT が発行できたとして（あるいは一時的に私の PAT を使うにしても）、それを git push のときに使う方法が分からなくて、それも調べないとなあとなっていました。

もし numa さんご存知でしたら教えてください :pray:

**Comment by aytdm** [comment]
ごめんなさい、こちら気付くのがおそくなりました :bow::bow::bow:

> 仮に PAT が発行できたとしてそれを git push のときに使う方法

[Github のドキュメント](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token)をみると、以下のように書いてあります。プロジェクトの secret に PAT を登録する流れになるんじゃないかなと思います。

> 1. Use or create a token with the appropriate permissions for that repository. For more information, see "Creating a personal access token."
> 2. Add the token as a secret in your workflow's repository, and refer to it using the ${{ secrets.SECRET_NAME }} syntax. For more information, see "Creating and using encrypted secrets."

ref: https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

先日ブランチが master から main に再度変更になったので、こちらはいったん仕切り直しましょうか:pray:

**Comment by aytdm** [comment]
仕切り直しのためクローズしますmm

**Comment by inouetakuya** [comment]
あああ、反応していなくてごめんなさい、クローズありがとうございました！ 🙇

**Comment by inouetakuya** [comment]
https://twitter.com/github/status/1390382527588798477

GitHub に良さそうな機能が追加されたので、同期にかかる手間がグッと減りそう。このくらいなら、時折手動でポチッとするくらいの運用でも良いかもしれない 📝
